version: "3.8"
   
services:
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./example:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  react:
    build:
      dockerfile: dockerfiles/Dockerfile.react
      context: .
    volumes:
      - ./example-react:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - web