FROM python:3.8

RUN apt update && apt upgrade -y
RUN curl --silent https://bootstrap.pypa.io/get-pip.py | python3.8

RUN pip3 install pipenv

ENV PYTHONUNBUFFERED=1

WORKDIR /code

COPY Pipfile Pipfile

COPY Pipfile.lock Pipfile.lock
RUN set -ex && pipenv install --deploy --system

COPY ./example/* /code/

